function XsThemePanel(){
var [st,setSt]=x.useState(function(){var a=window.XSTheme?window.XSTheme.getState():null;return a||{mode:"glass",primary:"#3B82F6",secondary:"",glass:{blur:16,panelAlpha:0.62,tint:0.18,saturate:1.4,radius:14},image:{name:"",colors:{}}};});
var [hex,setHex]=x.useState(st.primary||"#3B82F6");
var [busy,setBusy]=x.useState(false);
var fileRef=x.useRef(null);
x.useEffect(function(){if(!window.XSTheme)return;return window.XSTheme.subscribe(function(s){setSt(s);setHex(s.primary);});},[]);
var ap=function(patch,opts){if(!window.XSTheme)return;setSt(window.XSTheme.apply(patch,opts));};
var g=st.glass||{blur:16,panelAlpha:0.62,tint:0.18,saturate:1.4,radius:14};
var presets=[["玄枢冰蓝","#3B82F6"],["玄青","#0EA5E9"],["赤焰","#E55318"],["紫宸","#8B5CF6"],["松翠","#10B981"],["鎏金","#F59E0B"],["绯樱","#EC4899"],["墨玉","#1F2937"]];
var setGlass=function(k,v){var ng=Object.assign({},g);ng[k]=v;ap({glass:ng});};
var onHex=function(v){setHex(v);if(/^#[0-9a-fA-F]{6}$/.test(v))ap({primary:v});};
var onPickFile=function(ev){var f=ev.target.files&&ev.target.files[0];if(!f)return;setBusy(true);var reader=new FileReader();reader.onload=function(){var img=new Image();img.onload=function(){var S=256,ratio=Math.min(1,S/Math.max(img.width,img.height)),w=Math.max(1,Math.round(img.width*ratio)),h=Math.max(1,Math.round(img.height*ratio)),cv=document.createElement("canvas");cv.width=w;cv.height=h;cv.getContext("2d").drawImage(img,0,0,w,h);var dataUrl=cv.toDataURL("image/jpeg",0.82),finish=function(cols){ap({primary:(cols&&cols.primary)||st.primary,secondary:(cols&&cols.secondary)||st.secondary,mode:"image",image:{name:f.name,extractedAt:Date.now(),colors:cols||{},dataUrl:dataUrl}});setBusy(false);if(cols&&cols.primary&&Ce.success)Ce.success("已从图片提取主题色");};if(window.XSTheme&&window.XSTheme.extractFromImage){window.XSTheme.extractFromImage(f).then(finish).catch(function(){finish(null);});}else{finish(null);}};img.src=reader.result;};reader.readAsDataURL(f);ev.target.value="";};
var glassy=st.mode==="glass"||st.mode==="image";
var rangeRow=function(label,key,min,max,step,fmt){return o.jsxs(F0,{label:label,children:[o.jsx("span",{className:"mr-3 w-12 text-right font-mono text-[12px] text-muted-foreground tabular-nums",children:fmt?fmt(g[key]):g[key]}),o.jsx("input",{type:"range",min:min,max:max,step:step,value:g[key],onChange:function(ev){setGlass(key,parseFloat(ev.target.value));},className:"w-40 accent-[#E55318] cursor-pointer"})]});};
return o.jsxs("div",{className:"bg-white dark:bg-card rounded-2xl shadow-[0_1px_4px_rgba(0,0,0,0.04)] overflow-hidden",children:[
o.jsxs("div",{className:"flex items-center gap-2.5 px-6 py-4 pb-2 text-[13px] font-semibold text-foreground border-b border-border/50",children:[o.jsx(nF,{className:"h-[18px] w-[18px] text-[#E55318]"}),"主题引擎 · 磨砂玻璃与取色"]}),
o.jsxs("div",{className:"px-6 py-4 space-y-1",children:[
o.jsx(F0,{label:"主题模式",description:"磨砂玻璃带实时模糊；纯色换肤零模糊开销；图片主题从照片自动取色",children:o.jsx(HD,{options:[{value:"glass",label:"磨砂玻璃"},{value:"flat",label:"纯色换肤"},{value:"image",label:"图片主题"}],value:st.mode,onChange:function(v){ap({mode:v});}})}),
o.jsxs(F0,{label:"预设主色",description:"一键套用全局主题色，Semi 与业务组件同时跟随",children:[o.jsx("div",{className:"flex flex-wrap items-center gap-2",children:presets.map(function(p){var active=st.primary&&st.primary.toLowerCase()===p[1].toLowerCase();return o.jsx("button",{type:"button",title:p[0],onClick:function(){ap({primary:p[1]});},className:se("h-7 w-7 rounded-full transition-transform hover:scale-110",active?"ring-2 ring-offset-2 ring-[#E55318]":"ring-1 ring-black/10 dark:ring-white/20"),style:{backgroundColor:p[1]}},p[1]);})})]}),
o.jsxs(F0,{label:"自定义主色",description:"拖动取色器或输入十六进制色值，实时生效",children:[o.jsxs("div",{className:"flex items-center gap-2.5",children:[o.jsx("input",{type:"color",value:/^#[0-9a-fA-F]{6}$/.test(hex)?hex:"#3B82F6",onChange:function(ev){onHex(ev.target.value);},className:"h-8 w-10 cursor-pointer rounded-md border border-black/10 bg-transparent p-0.5 dark:border-white/15"}),o.jsx("input",{value:hex,onChange:function(ev){onHex(ev.target.value);},placeholder:"#3B82F6",className:"h-8 w-28 rounded-lg border border-black/10 bg-black/[0.03] px-2.5 font-mono text-[12px] uppercase outline-none focus:border-[#E55318] dark:border-white/15 dark:bg-white/5"})]})]}),
glassy?rangeRow("模糊半径","blur",0,30,1,function(v){return v+"px";}):null,
glassy?rangeRow("面板不透明度","panelAlpha",0.1,0.95,0.01,function(v){return Math.round(v*100)+"%";}):null,
glassy?rangeRow("色调浓度","tint",0,0.5,0.01,function(v){return Math.round(v*100)+"%";}):null,
glassy?rangeRow("色彩饱和","saturate",1,2,0.05,function(v){return v.toFixed(2)+"x";}):null,
o.jsxs(F0,{label:"从图片生成主题",description:"纯本地 Canvas 取色，不上传图片；自动提取主色/辅色并生成氛围背景",children:o.jsxs("div",{className:"flex items-center gap-2.5",children:[o.jsx("input",{ref:fileRef,type:"file",accept:"image/*",className:"hidden",onChange:onPickFile}),o.jsxs(Fe,{size:"sm",variant:"outline",className:"rounded-lg h-9",disabled:busy,onClick:function(){fileRef.current&&fileRef.current.click();},children:[busy?o.jsx(rn,{className:"mr-1.5 h-4 w-4 animate-spin"}):null,busy?"取色中…":"选择图片取色"]}),st.image&&st.image.name?o.jsx("span",{className:"max-w-[220px] truncate text-[12px] text-muted-foreground",children:st.image.name}):null]})}),
o.jsxs("div",{className:"flex justify-end pt-1",children:o.jsx(Fe,{size:"sm",variant:"ghost",className:"h-8 text-[12px] text-muted-foreground hover:text-foreground",onClick:function(){window.XSTheme&&window.XSTheme.reset();if(window.XSTheme)setSt(window.XSTheme.getState());} ,children:"恢复默认皮肤"})})
]})]});}
